### ISSUE TITLE
GNN: graph2vec

### ISSUE THREAD

**Issue by christam96** [christam96/Blockchain-GNN-Research#27]
# graph2vec

Find transaction subgraph embedding using graph2vec model.

## Todo
- [x] Read [graph2vec paper](https://arxiv.org/abs/1707.05005) (#28)
- [x] Find publicly available implementation of graph2vec ([here](https://karateclub.readthedocs.io/en/latest/modules/root.html#karateclub.graph_embedding.graph2vec.Graph2Vec))
- [x] Build data pipeline using `Ethereum 2nd-order transaction` data  (#33)
- [x] Obtain subgraph embeddings from `Ethereum 2nd-order transaction` data (#35)
- [X] Classify embeddings using SVM (#36)
   - [X] Set up downstream SVM classifier
   - [X] Create train/test datasets
   - [X] Generate prediction
